### ISSUE TITLE
import mssql_dataframe throws OverflowError

### ISSUE THREAD

**Issue by sghosh-simcoachgames** [jwcook23/mssql_dataframe#43]
Executing import mssql_dataframe throws following error:

`C:\PycharmProjects\step1_automation\venv\Scripts\python.exe C:\PycharmProjects\step1_automation\test\test_mssql.py 
Traceback (most recent call last):
  File "conversion.pyx", line 501, in pandas._libs.tslibs.conversion.convert_datetime_to_tsobject
OverflowError: Overflow occurred in npy_datetimestruct_to_datetime

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\PycharmProjects\step1_automation\test\test_mssql.py", line 1, in <module>
    import mssql_dataframe
  File "C:\PycharmProjects\step1_automation\venv\Lib\site-packages\mssql_dataframe\__init__.py", line 4, in <module>
    from mssql_dataframe.package import SQLServer  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PycharmProjects\step1_automation\venv\Lib\site-packages\mssql_dataframe\package.py", line 7, in <module>
    from mssql_dataframe.core import (
  File "C:\PycharmProjects\step1_automation\venv\Lib\site-packages\mssql_dataframe\core\conversion.py", line 11, in <module>
    from mssql_dataframe.core import (
  File "C:\PycharmProjects\step1_automation\venv\Lib\site-packages\mssql_dataframe\core\conversion_rules.py", line 100, in <module>
    "min_value": pd.Timestamp(pd.Timestamp.min, tz="UTC"),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "timestamps.pyx", line 1865, in pandas._libs.tslibs.timestamps.Timestamp.__new__
  File "conversion.pyx", line 412, in pandas._libs.tslibs.conversion.convert_to_tsobject
  File "conversion.pyx", line 504, in pandas._libs.tslibs.conversion.convert_datetime_to_tsobject
pandas._libs.tslibs.np_datetime.OutOfBoundsDatetime: Out of bounds nanosecond timestamp

Process finished with exit code 1
`
Python 3.11.5
mssql-dataframe 3.0.0
pyodbc 5.0.1
pandas 2.2.0

**Comment by jwcook23** [comment]
@jrecasens @sghosh-simcoachgames This was due to a newer version of pandas. I ran into the same issue when releasing v3.1.1 and this is fixed in this version.
